// website/src/components/ArticleCard.tsx
import { DEFAULT_APPEARANCE, type AppearanceSettings } from '@/lib/appearance';

type ArticleCardProps = {
  title?: string | null;
  description?: string | null;
  link?: string | null;
  imageUrl?: string | null;
  feedTitle?: string | null;
  pubDate?: Date | null;
  locale: string;
  readMoreLabel: string;
  fromFeedLabel: string;
  publishedAtLabel: string;
  appearance?: Partial<AppearanceSettings>;
};

export default function ArticleCard({
  title,
  description,
  link,
  imageUrl,
  feedTitle,
  pubDate,
  locale,
  readMoreLabel,
  fromFeedLabel,
  publishedAtLabel,
  appearance,
}: ArticleCardProps) {
  const settings = { ...DEFAULT_APPEARANCE, ...appearance };
  const safeLink = getSafeExternalLink(link);
  const proxiedImage = settings.showImages ? getProxiedImageUrl(imageUrl) : null;
  const isHeadline = settings.cardStyle === 'headline';
  const isCompact = settings.cardStyle === 'compact' || settings.cardStyle === 'dense';
  const showDescription = settings.showDescription && !isHeadline && description && settings.descriptionLines > 0;
  const articleClass = [
    'article-card bg-white border border-gray-200 transition dark:bg-gray-950 dark:border-gray-800',
    settings.cardStyle === 'minimal' ? 'rounded p-4' : 'rounded-lg hover:shadow-sm',
    settings.cardStyle === 'dense' ? 'p-3' : settings.density === 'dense' ? 'p-3' : 'p-5',
    settings.design === 'terminal' ? 'font-mono' : '',
  ].join(' ');
  const titleClass = isHeadline || isCompact ? 'text-base font-semibold' : 'text-lg font-semibold';

  return (
    <article
      className={articleClass}
      data-card-style={settings.cardStyle}
      data-design={settings.design}
      data-accent={settings.accentColor}
      data-font-scale={settings.fontScale}
      data-density={settings.density}
    >
      <div className={proxiedImage && !isCompact ? 'grid gap-4 sm:grid-cols-[160px_1fr]' : ''}>
        {proxiedImage && !isHeadline && (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={proxiedImage}
            alt=""
            loading="lazy"
            referrerPolicy="no-referrer"
            className={
              isCompact
                ? 'mb-3 h-28 w-full rounded object-cover'
                : 'h-36 w-full rounded object-cover sm:h-full'
            }
          />
        )}

        <div>
          <h2 className={`${titleClass} mb-1`}>
            {safeLink ? (
              <a
                href={safeLink}
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-700 hover:text-blue-900 hover:underline dark:text-blue-300 dark:hover:text-blue-200"
              >
                {title ?? 'Untitled'}
              </a>
            ) : (
              title ?? 'Untitled'
            )}
          </h2>

          {showDescription && (
            <p
              className="text-gray-600 text-sm mt-1 dark:text-gray-300"
              style={{
                display: '-webkit-box',
                WebkitLineClamp: settings.descriptionLines,
                WebkitBoxOrient: 'vertical',
                overflow: 'hidden',
              }}
            >
              {description}
            </p>
          )}

          {(settings.showSource || settings.showDate) && (
            <div className="flex flex-wrap items-center gap-3 mt-3 text-xs text-gray-400">
              {settings.showSource && feedTitle && (
                <span>
                  {fromFeedLabel}: {feedTitle}
                </span>
              )}
              {settings.showDate && pubDate && (
                <span>
                  {publishedAtLabel}: {pubDate.toLocaleDateString(locale, {
                    year: 'numeric',
                    month: 'short',
                    day: 'numeric',
                  })}
                </span>
              )}
            </div>
          )}

          {settings.showReadMore && safeLink && settings.cardStyle !== 'headline' && (
            <a
              href={safeLink}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-block mt-2 text-sm text-blue-600 hover:text-blue-800 dark:text-blue-300"
            >
              {readMoreLabel} &rarr;
            </a>
          )}
        </div>
      </div>
    </article>
  );
}

function getSafeExternalLink(link?: string | null) {
  if (!link) return null;
  try {
    const url = new URL(link);
    return ['http:', 'https:'].includes(url.protocol) ? url.href : null;
  } catch {
    return null;
  }
}

function getProxiedImageUrl(imageUrl?: string | null) {
  if (!imageUrl) return null;
  try {
    const url = new URL(imageUrl);
    if (!['http:', 'https:'].includes(url.protocol)) return null;
    return `/api/image?src=${encodeURIComponent(url.href)}`;
  } catch {
    return null;
  }
}

// website/web/src/lib/components/ArticleCard.svelte
<script lang="ts">
  import type { Article } from '$lib/api';
  import { appearance } from '$lib/appearance';
  import { t } from '$lib/i18n';

  let {
    article,
    ontoggleread,
  }: { article: Article; ontoggleread?: (read: boolean) => void } = $props();

  const a = appearance;

  function host(link: string | null): string {
    if (!link) return '';
    try {
      return new URL(link).hostname.replace(/^www\./, '');
    } catch {
      return '';
    }
  }

  function formatDate(s: string | null): string {
    if (!s) return '';
    const d = new Date(s);
    if (isNaN(d.getTime())) return '';
    return d.toLocaleDateString(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
  }

  // Cache-proxied image via the Go backend (never hot-links third parties).
  function imgSrc(url: string | null): string | null {
    if (!url) return null;
    return `/api/image?url=${encodeURIComponent(url)}`;
  }
</script>

<article
  class="surface overflow-hidden transition-shadow hover:shadow-sm"
  style="padding: var(--card-pad); opacity: {article.read ? 0.55 : 1};"
  data-card-style={$a.cardStyle}
  data-design={$a.design}
  data-read={article.read}
>
  <div class="flex gap-3" class:flex-col={$a.cardStyle === 'magazine'}>
    {#if $a.showImages && $a.cardStyle !== 'headline' && article.image_url}
      <img
        src={imgSrc(article.image_url)}
        alt=""
        loading="lazy"
        class="w-full object-cover"
        class:rounded-md={true}
        style={$a.cardStyle === 'compact'
          ? 'width:6rem;height:6rem;flex:none;'
          : 'max-height:14rem;'}
      />
    {/if}

    <div class="min-w-0 flex-1">
      <div class="mb-1 flex items-center gap-2 text-xs text-muted">
        {#if $a.showSource && host(article.link)}<span>{host(article.link)}</span>{/if}
        {#if $a.showSource && $a.showDate && formatDate(article.pub_date)}<span>·</span>{/if}
        {#if $a.showDate && formatDate(article.pub_date)}<span>{formatDate(article.pub_date)}</span>{/if}
        {#if ontoggleread}
          <button
            class="ml-auto shrink-0 rounded px-2 py-0.5 transition-colors hover:underline"
            onclick={() => ontoggleread?.(!article.read)}
            title={article.read ? 'Mark as unread' : 'Mark as read'}
          >
            {article.read ? '○ Unread' : '✓ Read'}
          </button>
        {/if}
      </div>

      <h2
        class="font-semibold leading-snug"
        class:text-lg={$a.cardStyle === 'magazine'}
        class:text-base={$a.cardStyle !== 'magazine'}
      >
        <a
          href={article.link ?? '#'}
          target="_blank"
          rel="noopener noreferrer nofollow"
          onclick={() => ontoggleread?.(true)}
          >{article.title ? stripTags(article.title) : 'Untitled'}</a
        >
      </h2>

      {#if $a.showDescription && $a.descriptionLines > 0 && $a.cardStyle !== 'headline' && article.description}
        <p
          class="mt-1 overflow-hidden text-sm text-muted"
          style="display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:{$a.descriptionLines};"
        >
          {stripTags(article.description)}
        </p>
      {/if}

      {#if $a.showReadMore && $a.cardStyle !== 'headline' && article.link}
        <a
          class="link-accent mt-2 inline-block text-sm"
          href={article.link}
          target="_blank"
          rel="noopener noreferrer nofollow"
          onclick={() => ontoggleread?.(true)}>{$t('home.readMore')} →</a
        >
      {/if}
    </div>
  </div>
</article>

<script lang="ts" module>
  // Strip tags and decode HTML entities from RSS descriptions (display only).
  export function stripTags(html: string): string {
    const stripped = html.replace(/<[^>]*>/g, '');
    const el = document.createElement('textarea');
    el.innerHTML = stripped;
    return el.value.trim();
  }
</script>
