// website/src/app/[locale]/statistics/page.tsx
import { getTranslations } from 'next-intl/server';
import { prisma } from '@/lib/prisma';

export default async function StatisticsPage() {
  const t = await getTranslations('statistics');

  const [userCount, feedCount, articleCount, topFeeds] = await Promise.all([
    prisma.user.count(),
    prisma.sourceFeed.count(),
    prisma.article.count(),
    prisma.sourceFeed.findMany({
      orderBy: { articles: { _count: 'desc' } },
      take: 10,
      include: { _count: { select: { articles: true } } },
    }),
  ]);

  return (
    <div>
      <h1 className="text-2xl font-bold mb-2">{t('title')}</h1>
      <p className="text-gray-500 mb-8">{t('subtitle')}</p>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
        <StatCard label={t('users')} value={userCount} />
        <StatCard label={t('feeds')} value={feedCount} />
        <StatCard label={t('articles')} value={articleCount} />
      </div>

      <h2 className="text-lg font-semibold mb-3">{t('topFeeds')}</h2>
      {topFeeds.length === 0 ? (
        <p className="text-gray-400 text-sm">{t('noFeeds')}</p>
      ) : (
        <div className="space-y-2">
          {topFeeds.map((feed, i) => (
            <div
              key={feed.id}
              className="bg-white border border-gray-200 rounded p-3 flex items-center justify-between"
            >
              <div className="min-w-0 mr-4">
                <span className="text-gray-400 text-sm mr-2">#{i + 1}</span>
                <span className="text-sm font-medium">{feed.title || feed.url}</span>
              </div>
              <span className="text-xs text-gray-400 shrink-0">
                {feed._count.articles} {t('articles').toLowerCase()}
              </span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function StatCard({ label, value }: { label: string; value: number }) {
  return (
    <div className="bg-white border border-gray-200 rounded-lg p-4 text-center">
      <p className="text-2xl font-bold text-blue-600">{value.toLocaleString()}</p>
      <p className="text-xs text-gray-500 mt-1">{label}</p>
    </div>
  );
}

// website/web/src/routes/statistics/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { getStatistics, type Statistics } from '$lib/api';
  import { t } from '$lib/i18n';

  let stats = $state<Statistics | null>(null);
  let error = $state<string | null>(null);

  onMount(async () => {
    try {
      stats = await getStatistics();
    } catch (e) {
      error = e instanceof Error ? e.message : 'Failed to load statistics';
    }
  });

  const statCards = $derived(
    stats
      ? [
          [$t('statistics.users'), stats.users],
          [$t('statistics.feeds'), stats.feeds],
          [$t('statistics.articles'), stats.articles],
        ]
      : [],
  );
</script>

<h1 class="mb-1 text-2xl font-semibold">{$t('statistics.title')}</h1>
<p class="mb-6 text-sm text-muted">{$t('statistics.subtitle')}</p>

{#if error}
  <p class="text-sm" style="color: #ef4444;">{error}</p>
{:else if !stats}
  <div class="grid grid-cols-1 gap-3 sm:grid-cols-3">
    {#each Array(3) as _}
      <div class="surface animate-pulse" style="height: 5rem;"></div>
    {/each}
  </div>
{:else}
  <section class="mb-8 grid grid-cols-1 gap-3 sm:grid-cols-3">
    {#each statCards as [label, value]}
      <div class="surface px-4 py-3">
        <p class="text-xs text-muted">{label}</p>
        <p class="mt-1 text-2xl font-semibold" style="color: var(--accent);">{value}</p>
      </div>
    {/each}
  </section>

  <h2 class="mb-3 text-lg font-semibold">{$t('statistics.topFeeds')}</h2>
  {#if stats.topFeeds.length === 0}
    <p class="text-muted">{$t('statistics.noFeeds')}</p>
  {:else}
    <ol class="space-y-2">
      {#each stats.topFeeds as feed, i}
        <li class="surface flex items-center justify-between gap-3 px-4 py-3">
          <div class="flex items-center gap-3 min-w-0">
            <span class="text-muted text-sm w-6 shrink-0">#{i + 1}</span>
            <div class="min-w-0">
              <p class="truncate font-medium">{feed.title ?? feed.url}</p>
              <p class="truncate text-xs text-muted">{feed.url}</p>
            </div>
          </div>
          <span class="shrink-0 text-sm text-muted">{feed.articleCount} {$t('statistics.articlesSuffix')}</span>
        </li>
      {/each}
    </ol>
  {/if}
{/if}
